// client/src/components/Navbar.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <router-link class="navbar-brand" to="/">This is IT</router-link>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <router-link class="nav-link" to="/about">About</router-link>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Knowledge</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Games</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
</template>

<script>
export default {
  name: 'Navbar',
  props: {
  }
}
</script>

// client/src/components/Navbar.tsx
import * as React from 'react';
import Navbar from 'react-bootstrap/Navbar';
import Container from 'react-bootstrap/Container';
import Nav from 'react-bootstrap/Nav';
import NavDropdown from 'react-bootstrap/NavDropdown';
import { Link } from 'react-router-dom'

function TIITNavbar({style}: {style: Object}) {
  return (
    <div>
      <Navbar collapseOnSelect expand="lg" bg="dark" variant="dark" style={style}>
        <Container>
          <Navbar.Brand as={Link} to="./">This is IT</Navbar.Brand>
          <Navbar.Toggle aria-controls="responsive-navbar-nav" />
          <Navbar.Collapse id="responsive-navbar-nav" role="navigation">
            <Nav className="me-auto">
              <NavDropdown title="Knowledge" id="collasible-nav-dropdown">
                <NavDropdown.Item as={Link} to="./knowledge">Info</NavDropdown.Item>
                <NavDropdown.Item as={Link} to="./karriere">Karriere</NavDropdown.Item>
              </NavDropdown>
              <NavDropdown title="Games" id="collasible-nav-dropdown">
                <NavDropdown.Item as={Link} to="./games/sqit/game1">SQIT</NavDropdown.Item>
                <NavDropdown.Item as={Link} to="./games/quiz">Quiz</NavDropdown.Item>
              </NavDropdown>
            </Nav>
            <Nav>
              <Nav.Link as={Link} to="./admin/dash">Admin</Nav.Link>
              <Nav.Link eventKey={2} as={Link} to="./admin/login">
                Login
              </Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
    </div>
  );
}

export default TIITNavbar;
